FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir --root-user-action=ignore -r requirements.txt
RUN apt-get update && \
    apt-get install -y \
    fonts-unifont \
    fonts-liberation \
    fonts-noto-cjk \
    fonts-noto-color-emoji \
    fonts-dejavu \
    && playwright install --with-deps chromium

COPY . .

EXPOSE 8000

CMD ["python", "main.py"]
